### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by peter7891** [chikaku/gosyn#1]
Hello,i am about to try to use this for a Go interpreter.
Can you identify where is the problematic utf8 decode, that you mentioned in the readme?

**Comment by chikaku** [comment]
The main issue is that the source code and tokens (comments/literal values) are stored as string types in the Scanner. Thus every time the source code or tokens need to be parsed, rollback, or length-calculated, `.chars().next` must be called to do utf-8 decode. The problem is that many decode process is repeated(which should be unnecessary).

For example:

`scanner::next_token` method need calculate new position after a token has been parsed by `Scanner::scan_token`

https://github.com/chikaku/gosyn/blob/a16a56b17ba9d5f984385900c4ac57752f184b25/src/scanner.rs#L178

and `char_count` call `chars().count()` which repeates utf-8 decode that has already been done once at `scan_token`

https://github.com/chikaku/gosyn/blob/a16a56b17ba9d5f984385900c4ac57752f184b25/src/token.rs#L266-L267

I am thinking of storing the source code as a `Vec<char>` type to eliminate this problem.
