### ISSUE TITLE
Parsing an invalid string panics, it should return an error

### ISSUE THREAD

**Issue by gbouv** [chikaku/gosyn#8]
Repro steps:
```
fn main() {
    let source = "# hello world";

    parse_source(source);
    println!("Did not panic");
}
```

It panics here: https://github.com/chikaku/gosyn/blob/b5c363ef490e7f9bf58909922a894dd13ab45d3d/src/parser.rs#L31

I don't know if it's intended or not, but the `from_file` returns a nice `Result<>` object. How would we feel about changing the signature of `from<S: AsRef<str>>(s: S) -> Self` to `from<S: AsRef<str>>(s: S) -> Result<Self>`?

if we're concerned about breaking the API here, we can always add an `panic_safe_from<S: AsRef<str>>(s: S) -> Result<Self>` and maybe deprecate the other. 

Wdyt? Let me know which one of the above improvements you prefer and I'm more than happy to submit a PR.

**Comment by gbouv** [comment]
Something like this would be ideal IMO: https://github.com/chikaku/gosyn/pull/9

**Comment by chikaku** [comment]
Thanks for your feedback! Here is what I think:

`Parser::from_file` should return an `Result<Parser>` because of file reading have a `io::Result`.
`Parser::from` (`from_str` actually) should just return an `Parser` intuitively, It is a constructor should NOT return `Result` or `Panic`.

The real issue is calling `Parser::next` within the constructor method. The original intent was to assign the first token to Parser.current.

Therefore, a simple solution would be to introduce a boolean flag `started` within Parser and if Parser not `started`, call `Parser::next` once. This code should be added to the front of all **public** methods, then we can remove `next()` in `Parser::from` method.

```rust
pub fn parse_file(&mut self) -> Result<ast::File> { ... }
pub fn expression(&mut self) -> Result<ast::Expression> { ... }  
pub fn parse_stmt(&mut self) -> Result<ast::Statement> { ... }
```

And the internal unit test code should also call `next` after `Parser::from` for example:

https://github.com/chikaku/gosyn/blob/b5c363ef490e7f9bf58909922a894dd13ab45d3d/src/parser.rs#L2302

We may need another PR if you are interested.

**Comment by gbouv** [comment]
Thanks for the quick response @chikaku ! Here is a new PR hopefully matching what you describe above: https://github.com/chikaku/gosyn/pull/10
Let me know if that works for you

**Comment by chikaku** [comment]
Fixed by #10. Thanks for the PR!

**Comment by chikaku** [comment]
@gbouv `v0.2.6` has been released.

**Comment by gbouv** [comment]
Thanks a lot 🙏
